name: Build project
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  linux_build:
    runs-on: ubuntu-latest
    steps:
      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install -yq build-essential git libssl-dev

      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build project
        run: make OTHER_CFLAGS="-Werror"