name: Run tests (Linux)
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  tests_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install -yq make git gcc pkg-config libssl-dev cmake ninja-build meson libffi-dev libgit2-dev

      - name: Clone main repository
        uses: actions/checkout@v3
        with:
          submodules: true
          path: osh-vpn

      - name: Clone Snaipe/Criterion repository
        uses: actions/checkout@v3
        with:
          repository: Snaipe/Criterion
          ref: v2.4.0
          submodules: recursive
          path: Criterion

      - name: Build and install Criterion
        run: |
          cd "$GITHUB_WORKSPACE/Criterion"
          meson --prefix=/usr build
          ninja -C build
          sudo ninja -C build install

      - name: Build and run tests
        run: |
          cd "$GITHUB_WORKSPACE/osh-vpn"
          mkdir build
          cd build
          cmake -G "Unix Makefiles" -DCMAKE_C_FLAGS="-Werror" -DCMAKE_BUILD_TYPE=Hardened -DENABLE_UNIT_TESTS=ON ..
          make
          ctest --output-on-failure