name: Run tests
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  linux_test:
    runs-on: ubuntu-latest
    steps:
      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install -yq make git gcc pkg-config libssl-dev cmake

      - name: Clone Snaipe/Criterion repository
        uses: actions/checkout@v2
        with:
          repository: Snaipe/Criterion
          ref: v2.3.3

      - name: Build and install Criterion
        run: |
          mkdir build
          cd build
          cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..
          make -j$(nproc)
          sudo make install

      - name: Clone main repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build and run tests
        run: |
          mkdir build
          cd build
          cmake -G "Unix Makefiles" -DCMAKE_C_FLAGS="-Werror" -DCMAKE_BUILD_TYPE=Hardened -DENABLE_UNIT_TESTS=1 ..
          make
          ctest --output-on-failure