name: Run unit tests
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  linux_test:
    runs-on: ubuntu-latest
    steps:
      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install -yq build-essential git libssl-dev

      - name: Clone Snaipe/Criterion repository
        uses: actions/checkout@v2
        with:
          repository: Snaipe/Criterion
          ref: v2.3.3

      - name: Build and install Criterion
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..
          make -j$(nproc)
          sudo make install

      - name: Clone main repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build and run unit tests
        run: make test -j$(nproc) OTHER_CFLAGS="-Werror"